export const MAIN_BLUE_COLOR = "#5C87DB"
export const PRIMARY_TEXT_COLOR = "#232323"
export const SECONDARY_TEXT_COLOR = "#5C5C5C"
export const GRAY_TEXT_COLOR = "#B7BAC1"
export const WHITE_TEXT_COLOR = "#FFFFFF"